BINANCE_SYMBOLS = [
        "DOGE/USDT", "KLAY/USDT", "MANA/USDT", "SAND/USDT", "ALGO/USDT", "HBAR/USDT", "ADA/USDT", "ALPHA/USDT",
        "PEOPLE/USDT", "SHIB/USDT", "EOS/USDT", "CFX/USDT", "XRP/USDT", "TRX/USDT", "ETH/USDT",
        "APT/USDT", "OP/USDT", "STX/USDT", "LQTY/USDT", "GALA/USDT", "DYDX/USDT", "CRV/USDT"
    ]

ANALISE_INTERVALS = ["1m", "5m", "15m", "30m", "1h", "2h", "4h", "1d", "1W", "1M"]

DEPTH_LIMIT = 400
UPDATE_TIME = 10
